import { getOpenAIClient } from "./openai";

export interface VideoPlan {
  prompts: string[];
  error?: string;
}

export async function generateVideoPlan(
  userPrompt: string,
  segmentCount: number
): Promise<VideoPlan> {
  const client = getOpenAIClient();
  
  const systemPrompt = `
You are an expert video director and screenwriter. 
Your task is to break down a user's video idea into a coherent sequence of ${segmentCount} distinct video segments.

Each segment will be generated by an AI video model (like Sora, Kling, or runway).
The segments should flow together logically to tell a story or demonstrate the concept.
They will be stitched together later, so continuity is important, but visual style should be consistent through the prompts.
However, each prompt must be self-contained enough for the model to generate a good 5-second clip.

Output MUST be a valid JSON object with a single key "prompts" which is an array of strings.
Example:
{
  "prompts": [
    "A cinematic wide shot of a futuristic city with flying cars...",
    "Close up of a protagonist looking up at the sky...",
    "The protagonist getting into a vehicle..."
  ]
}
`;

  try {
    const response = await client.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: `Create a ${segmentCount}-segment video plan for: "${userPrompt}"` },
      ],
      response_format: { type: "json_object" },
    });

    const content = response.choices[0].message.content;
    if (!content) {
      throw new Error("No content generated");
    }

    const parsed = JSON.parse(content);
    if (!Array.isArray(parsed.prompts) || parsed.prompts.length !== segmentCount) {
      // Fallback if count creates mismatch, though rare with gpt-4o
      // If we got some prompts, maybe just use them or pad/slice
      if (Array.isArray(parsed.prompts)) {
         return { prompts: parsed.prompts.slice(0, segmentCount) };
      }
      throw new Error("Invalid JSON structure");
    }

    return { prompts: parsed.prompts };
  } catch (error) {
    console.error("Failed to generate video plan:", error);
    return { 
      prompts: [], 
      error: error instanceof Error ? error.message : "Unknown error" 
    };
  }
}
